Repository sopt-makers/sopt-backend, pull requests merged in 2022-12, with the labels that each got.

#22 스탬프 관련 기능 API
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/domain/entity/BaseEntity.java
  src/main/java/org/sopt/app/domain/entity/Stamp.java
  src/main/java/org/sopt/app/interfaces/postgres/StampRepository.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
  src/main/java/org/sopt/app/presentation/stamp/dto/StampRequestDto.java
  src/main/java/org/sopt/app/presentation/stamp/dto/StampResponseDto.java
Labels: size/L

#23 Mission 컬럼 타입 수정
  src/main/resources/database/create.sql
Labels: size/XS

#24 feature/mission
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/interfaces/postgres/StampRepository.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
Labels: size/M

#25 Stamp 등록 삭제 시 점수 update, 한마디 편집 Api 추가
  src/main/java/org/sopt/app/application/rank/RankService.java
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/domain/entity/User.java
  src/main/java/org/sopt/app/presentation/rank/RankController.java
  src/main/java/org/sopt/app/presentation/rank/dto/UserProfileRequestDto.java
Labels: size/L

#26 feat: 날짜 타입을 yyyy-MM-dd로 변경
  src/main/java/org/sopt/app/domain/entity/BaseEntity.java
Labels: size/XS

#27 feat: 랭킹 목록 조회 추가
  src/main/java/org/sopt/app/application/rank/RankService.java
  src/main/java/org/sopt/app/presentation/rank/RankController.java
  src/main/java/org/sopt/app/presentation/rank/dto/RankResponseDto.java
Labels: size/L

#28 feat: 랭킹 상세조회 API 추가
  src/main/java/org/sopt/app/application/rank/RankService.java
  src/main/java/org/sopt/app/presentation/rank/RankController.java
  src/main/java/org/sopt/app/presentation/rank/dto/FindAllRanksResponseDto.java
  src/main/java/org/sopt/app/presentation/rank/dto/FindRankResponseDto.java
Labels: size/M
