Repository sopt-makers/sopt-backend, pull requests merged in 2023-01, with the labels that each got.

#29 feat: 회원가입 시 default point 0으로 설정
  src/main/java/org/sopt/app/application/user/service/UserService.java
  src/main/java/org/sopt/app/domain/entity/User.java
Labels: size/L

#30 [Fix] 닉네임 변경 시 json 형식 그대로 값이 담기는 현상 수정
  src/main/java/org/sopt/app/presentation/auth/AuthController.java
  src/main/java/org/sopt/app/presentation/auth/dto/ChangeNicknameRequestDto.java
Labels: size/S

#31 feat: 탈퇴하기 API
  src/main/java/org/sopt/app/application/auth/AuthUseCaseImpl.java
  src/main/java/org/sopt/app/common/exception/DbException.java
  src/main/java/org/sopt/app/presentation/auth/AuthController.java
Labels: size/M

#32 refactor: 비밀번호 변경 API 수정
  src/main/java/org/sopt/app/application/user/dto/SignUpUserDto.java
  src/main/java/org/sopt/app/presentation/auth/AuthController.java
  src/main/java/org/sopt/app/presentation/auth/dto/ChangePasswordRequestDto.java
Labels: size/S

#33 [Fix] 스탬프 등록시 중복 등록 방지
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/common/ResponseCode.java
  src/main/java/org/sopt/app/common/exception/ApiExceptionHandler.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
Labels: size/M

#34 firebase 연동을 위한 api 추가
  src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
  src/main/java/org/sopt/app/presentation/firebase/dto/FirebaseResponseDto.java
Labels: size/M

#35 [Fix] FirebaseResponse 수정
  src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
  src/main/java/org/sopt/app/presentation/firebase/dto/FirebaseResponseDto.java
Labels: size/S
