Repository sopt-makers/sopt-backend, pull requests merged in 2023-12, with the labels that each got.

#152 Feat/#151 poke new
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/M

#163 Feat/#154 friends friend recommend
  src/main/java/org/sopt/app/application/friend/FriendInfo.java
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/user/UserInfo.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendCustomRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepositoryImpl.java
  src/main/java/org/sopt/app/interfaces/postgres/UserCustomRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepositoryImpl.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/L

#164 Feat/#161 poke friend
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/user/UserInfo.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/L

#165 Feat/#157 get after poke
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/poke/PokeInfo.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/domain/enums/Friendship.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/external/PlaygroundClient.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/L

#170 Feat/#169 get detail friend list
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/domain/enums/Friendship.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/L

#168 Feat/#167 get simple friend list
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/domain/enums/Friendship.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/L

#166 Feat/#158 get poke to me single
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthInfo.java
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/domain/enums/Friendship.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/external/PlaygroundClient.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/L

#172 Feat/#171 get poke message
  src/main/java/org/sopt/app/application/poke/PokeInfo.java
  src/main/java/org/sopt/app/application/poke/PokeMessageService.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/domain/entity/PokeMessage.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageType.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageTypeConverter.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeMessageRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
  src/main/resources/database/create.sql
Labels: size/L

#173 Feat/#161 poke friend
  src/main/java/org/sopt/app/application/friend/FriendInfo.java
  src/main/java/org/sopt/app/application/user/UserInfo.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/L

#174 FIX : 클라이언트 Response DTO 형식 수정 요청 반영
  src/main/java/org/sopt/app/application/poke/PokeInfo.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/M

#176 Sprint2 -> Dev로 반영
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthInfo.java
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/poke/PokeEvent.java
  src/main/java/org/sopt/app/application/poke/PokeEventListener.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/poke/PokeInfo.java
  src/main/java/org/sopt/app/application/poke/PokeMessageService.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/application/user/UserInfo.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/config/QuerydslConfiguration.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/domain/entity/Friend.java
  src/main/java/org/sopt/app/domain/entity/PokeHistory.java
  src/main/java/org/sopt/app/domain/entity/PokeMessage.java
  src/main/java/org/sopt/app/domain/enums/Friendship.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageType.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageTypeConverter.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/external/PlaygroundClient.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendCustomRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepositoryImpl.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeMessageRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserCustomRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepositoryImpl.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeRequest.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
  src/main/java/org/sopt/app/presentation/user/UserRequest.java
  src/main/resources/database/create.sql
Labels: size/XXL

#177 fix: pg memberProfile dto json 매핑 수정
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthInfo.java
Labels: size/XS

#175 FIX : 기획 요구사항에 따른 `PokeMessageType` 정정
  src/main/java/org/sopt/app/domain/enums/PokeMessageType.java
Labels: size/XS

#178 Merge `dev` branch from `sprint2/poke` branch
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthInfo.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageType.java
Labels: size/XS

#179 fix: friend 저장 오류 수정
  src/main/java/org/sopt/app/application/poke/FriendService.java
Labels: size/XS

#180 fix: 친구가 아직 없을 때 빈 값 리턴
  src/main/java/org/sopt/app/facade/PokeFacade.java
Labels: size/XS

#181 Fix/poke logic structure
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/poke/PokeInfo.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/L

#182 fix: pgId 추가 및 isAlreadyPoke 변경
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/poke/PokeInfo.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendCustomRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepositoryImpl.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/M

#183 fix: poke isReply 방식 변경
  src/main/java/org/sopt/app/application/poke/PokeService.java
Labels: size/XS

#184 fix: 친구 기준 변경
  src/main/java/org/sopt/app/domain/enums/Friendship.java
Labels: size/XS

#185 Fix/relation type fix
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/domain/enums/Friendship.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
Labels: size/S

#186 fix: pokeMessage Facade 변경
  src/main/java/org/sopt/app/application/poke/PokeMessageService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeMessageRepository.java
Labels: size/M

#187 fix: 날 찌른 친구 불러오는 로직 수정
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
Labels: size/S

#188 fix: friendList Response에 totalSize 추가
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/S

#190 fix: FriendList size 정상적으로 수정
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
Labels: size/S

#191 fix: pageSize 관계없이 항상 전체 크기 반환
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
Labels: size/S

#192 fix: Friend 응답 디폴트 값 수정
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
Labels: size/S

#193 fix: 이미 찌른 경우 에러 처리
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
Labels: size/XS

#194 fix: user profileImage 빈스트링 처리
  src/main/java/org/sopt/app/facade/PokeFacade.java
Labels: size/XS

#196 fix: totalPageSize response 추가
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/S
