Repository sopt-makers/sopt-backend, pull requests merged in 2023-03, with the labels that each got.

#38 [APP-37] docs: 솝탬프 readme.md 작성
  README.md
Labels: size/M

#40 refactor: stamp
  build.gradle
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/common/ResponseCode.java
  src/main/java/org/sopt/app/common/exception/BadRequestException.java
  src/main/java/org/sopt/app/common/exception/EntityNotFoundException.java
  src/main/java/org/sopt/app/common/s3/S3Service.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
  src/main/java/org/sopt/app/presentation/stamp/StampRequest.java
  src/main/java/org/sopt/app/presentation/stamp/StampResponse.java
  src/main/java/org/sopt/app/presentation/stamp/StampResponseMapper.java
  src/main/java/org/sopt/app/presentation/stamp/dto/StampRequestDto.java
  src/main/java/org/sopt/app/presentation/stamp/dto/StampResponseDto.java
  src/main/resources/application.yml
Labels: refactor, size/XL

#46 feature: auth, user
  build.gradle
  src/main/java/org/sopt/app/application/auth/AuthUseCaseImpl.java
  src/main/java/org/sopt/app/application/auth/CustomUserDetailService.java
  src/main/java/org/sopt/app/application/auth/EncryptService.java
  src/main/java/org/sopt/app/application/auth/JwtTokenService.java
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthInfo.java
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/mission/MissionService.java
  src/main/java/org/sopt/app/application/rank/RankInfo.java
  src/main/java/org/sopt/app/application/rank/RankService.java
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/application/user/UserInfo.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/application/user/UserUseCase.java
  src/main/java/org/sopt/app/application/user/UserUseCaseImpl.java
  src/main/java/org/sopt/app/application/user/dto/LogInUserDto.java
  src/main/java/org/sopt/app/application/user/dto/SignUpUserDto.java
  src/main/java/org/sopt/app/application/user/service/UserService.java
  src/main/java/org/sopt/app/common/ResponseCode.java
  src/main/java/org/sopt/app/common/config/JwtAuthenticationFilter.java
  src/main/java/org/sopt/app/common/config/JwtExceptionFilter.java
  src/main/java/org/sopt/app/common/config/OpenApiConfig.java
  src/main/java/org/sopt/app/common/config/SecurityConfiguration.java
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
  src/main/java/org/sopt/app/common/exception/UnauthorizedException.java
  src/main/java/org/sopt/app/domain/entity/User.java
  src/main/java/org/sopt/app/interfaces/postgres/MissionRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepository.java
  src/main/java/org/sopt/app/presentation/BaseController.java
  src/main/java/org/sopt/app/presentation/HealthCheckController.java
  src/main/java/org/sopt/app/presentation/auth/AuthController.java
  src/main/java/org/sopt/app/presentation/auth/AuthRequest.java
  src/main/java/org/sopt/app/presentation/auth/AuthResponse.java
  src/main/java/org/sopt/app/presentation/auth/AuthResponseMapper.java
  src/main/java/org/sopt/app/presentation/auth/dto/ChangeNicknameRequestDto.java
  src/main/java/org/sopt/app/presentation/auth/dto/ChangePasswordRequestDto.java
  src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
  src/main/java/org/sopt/app/presentation/firebase/FirebaseResponse.java
  src/main/java/org/sopt/app/presentation/firebase/dto/FirebaseResponseDto.java
  src/main/java/org/sopt/app/presentation/mission/MissionController.java
  src/main/java/org/sopt/app/presentation/rank/RankController.java
  src/main/java/org/sopt/app/presentation/rank/RankResponse.java
  src/main/java/org/sopt/app/presentation/rank/RankResponseMapper.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
  src/main/java/org/sopt/app/presentation/stamp/StampResponse.java
  src/main/java/org/sopt/app/presentation/user/UserController.java
  src/main/java/org/sopt/app/presentation/user/UserRequest.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
  src/main/java/org/sopt/app/presentation/user/request/CreateUserRequest.java
  src/main/java/org/sopt/app/presentation/user/request/LogInUserRequest.java
  src/main/java/org/sopt/app/presentation/user/response/LoginResponse.java
  src/main/java/org/sopt/app/presentation/user/response/SignUpResponse.java
Labels: enhancement, refactor, size/XXL
