Repository sopt-makers/sopt-backend, pull requests merged in 2023-10, with the labels that each got.

#110 Feat/#88 connect push server
  .gitignore
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
  src/main/java/org/sopt/app/domain/entity/Notification.java
  src/main/java/org/sopt/app/domain/enums/NotificationCategory.java
  src/main/java/org/sopt/app/domain/enums/NotificationType.java
  src/main/java/org/sopt/app/interfaces/postgres/NotificationRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepository.java
  src/main/java/org/sopt/app/presentation/notification/NotificationController.java
  src/main/java/org/sopt/app/presentation/notification/NotificationRequest.java
  src/main/java/org/sopt/app/presentation/notification/NotificationResponse.java
  src/main/java/org/sopt/app/presentation/notification/NotificationResponseMapper.java
  src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
  src/main/resources/database/create.sql
  src/main/resources/http/default.http
  src/main/resources/http/request/AuthDev.http
  src/main/resources/http/request/AuthLocal.http
  src/main/resources/http/request/develop.http
  src/main/resources/http/request/local.http
  src/main/resources/http/request/local/ExternalPushToken.http
Labels: enhancement, size/L

#112 Fix/#111 fix notification schema
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/domain/entity/Notification.java
  src/main/java/org/sopt/app/interfaces/postgres/NotificationRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepository.java
  src/main/java/org/sopt/app/presentation/notification/NotificationController.java
  src/main/java/org/sopt/app/presentation/notification/NotificationRequest.java
  src/main/java/org/sopt/app/presentation/notification/NotificationResponse.java
  src/main/resources/database/create.sql
Labels: size/M

#114 FIX : 알림서버 등록 시 DB 내 해당 토큰 잔존 여부 검사 제거
  src/main/java/org/sopt/app/application/notification/PushTokenService.java
Labels: size/XS

#117 Feat/#115 notification detail api
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/presentation/notification/NotificationController.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
Labels: size/M

#122 Fix/#121 notification dto fix
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/domain/entity/Notification.java
  src/main/java/org/sopt/app/domain/enums/NotificationType.java
  src/main/java/org/sopt/app/presentation/notification/NotificationRequest.java
  src/main/resources/database/create.sql
Labels: size/S

#119 FIX : 알림 저장시간 timezone 한국시간대로 수정
  src/main/java/org/sopt/app/domain/entity/Notification.java
Labels: size/XS, fix

#124 Fix/#123 timezone difference
  src/main/java/org/sopt/app/AppApplication.java
  src/main/java/org/sopt/app/domain/entity/BaseEntity.java
  src/main/java/org/sopt/app/domain/entity/Notification.java
Labels: bug, size/M, fix

#126 Fix/#125 delete option domain
  src/main/java/org/sopt/app/application/notification/NotificationOptionService.java
  src/main/java/org/sopt/app/domain/entity/User.java
  src/main/java/org/sopt/app/domain/entity/UserNotificationOption.java
  src/main/java/org/sopt/app/interfaces/postgres/UserNotificationOptionRepository.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthController.java
  src/main/java/org/sopt/app/presentation/notification/OptionRequest.java
  src/main/java/org/sopt/app/presentation/notification/OptionResponse.java
  src/main/java/org/sopt/app/presentation/notification/OptionResponseMapper.java
  src/main/java/org/sopt/app/presentation/user/UserPushTokenController.java
  src/main/resources/database/create.sql
Labels: size/L

#129 Fix/#127 Push Token 도메인 구조 변경 및 탈퇴 API 완상
  .gitignore
  src/main/java/org/sopt/app/application/notification/PushTokenService.java
  src/main/java/org/sopt/app/domain/entity/PushToken.java
  src/main/java/org/sopt/app/domain/entity/PushTokenPK.java
  src/main/java/org/sopt/app/domain/enums/PushTokenPlatform.java
  src/main/java/org/sopt/app/interfaces/postgres/PushTokenRepository.java
  src/main/java/org/sopt/app/presentation/user/UserPushTokenController.java
  src/main/java/org/sopt/app/presentation/user/UserWithdrawController.java
  src/main/resources/database/create.sql
  src/main/resources/http/request/AuthDev.http
  src/main/resources/http/request/AuthLocal.http
  src/main/resources/http/request/local/ExternalPushToken.http
  src/main/resources/http/request/local/Firebase.http
  src/main/resources/http/request/local/Mission.http
  src/main/resources/http/request/local/Rank.http
  src/main/resources/http/request/local/Stamp.http
  src/main/resources/http/request/local/UserBasic.http
  src/main/resources/http/request/local/UserNotification.http
  src/main/resources/http/request/local/UserOriginal.http
  src/main/resources/http/request/local/UserPushToken.http
Labels: size/L

#131 Refactor/#130 facade layer
  README.md
  build.gradle
  src/main/java/org/sopt/app/application/stamp/StampInfo.java
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
  src/main/java/org/sopt/app/facade/DescriptionFacade.java
  src/main/java/org/sopt/app/facade/SoptampFacade.java
  src/main/java/org/sopt/app/facade/UserFacade.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthController.java
  src/main/java/org/sopt/app/presentation/description/DescriptionController.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
  src/main/java/org/sopt/app/presentation/stamp/StampResponseMapper.java
  src/main/java/org/sopt/app/presentation/user/UserController.java
  src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
Labels: size/L, refactor

#132 HOTFIX : MainView Response Field 이름 변경 및 `isAllConfirm` 의미에 맞는 연산으로 수정
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
Labels: size/XS

#138 feat: pg 토큰 갱신 시 pg 토큰 저장
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
Labels: size/S

#134 Request merge Main to Dev
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
Labels: size/S

#140 fix: refresh decode 시 에러 핸들링 추가
  src/main/java/org/sopt/app/application/auth/JwtTokenService.java
Labels: size/S
