Repository sopt-makers/sopt-backend, pull requests merged in 2023-09, with the labels that each got.

#82 Feat/#80 active user ranking
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthInfo.java
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/rank/RankService.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepository.java
  src/main/java/org/sopt/app/presentation/rank/RankController.java
  src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
Labels: size/L

#85 Feat/#83 main description api
  src/main/java/org/sopt/app/application/description/DescriptionInfo.java
  src/main/java/org/sopt/app/application/description/DescriptionService.java
  src/main/java/org/sopt/app/domain/entity/MainDescription.java
  src/main/java/org/sopt/app/interfaces/postgres/MainDescriptionRepository.java
  src/main/java/org/sopt/app/presentation/description/DescriptionController.java
  src/main/java/org/sopt/app/presentation/description/DescriptionResponse.java
  src/main/resources/database/create.sql
Labels: size/L

#84 refactor: mission의 display 속성 반영
  src/main/java/org/sopt/app/application/mission/MissionService.java
  src/main/java/org/sopt/app/interfaces/postgres/MissionRepository.java
Labels: size/S

#87 fix: swagger description 수정
  src/main/java/org/sopt/app/presentation/description/DescriptionController.java
Labels: size/XS

#86 Feat/#79 alarm dtk
  .gitignore
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/notification/NotificationOptionService.java
  src/main/java/org/sopt/app/application/notification/PushTokenService.java
  src/main/java/org/sopt/app/application/user/UserInfo.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/domain/entity/PushToken.java
  src/main/java/org/sopt/app/domain/entity/PushTokenPK.java
  src/main/java/org/sopt/app/domain/entity/User.java
  src/main/java/org/sopt/app/domain/entity/UserNotificationOption.java
  src/main/java/org/sopt/app/interfaces/postgres/PushTokenRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserNotificationOptionRepository.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthController.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthRequest.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthResponse.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthResponseMapper.java
  src/main/java/org/sopt/app/presentation/auth/PlaygroundAuthRequest.java
  src/main/java/org/sopt/app/presentation/auth/PlaygroundAuthResponse.java
  src/main/java/org/sopt/app/presentation/notification/NotificationRequest.java
  src/main/java/org/sopt/app/presentation/notification/OptionRequest.java
  src/main/java/org/sopt/app/presentation/notification/OptionResponse.java
  src/main/java/org/sopt/app/presentation/notification/OptionResponseMapper.java
  src/main/java/org/sopt/app/presentation/notification/PushTokenRequest.java
  src/main/java/org/sopt/app/presentation/notification/PushTokenResponse.java
  src/main/java/org/sopt/app/presentation/notification/PushTokenResponseMapper.java
  src/main/java/org/sopt/app/presentation/user/UserNotificationController.java
  src/main/java/org/sopt/app/presentation/user/UserRequest.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
  src/main/java/org/sopt/app/presentation/user/UserWithdrawController.java
  src/main/resources/database/create.sql
  src/main/resources/http/default.http
  src/main/resources/http/request/Auth.http
  src/main/resources/http/request/develop.http
  src/main/resources/http/request/local.http
  src/main/resources/http/request/local/ExternalPushToken.http
  src/main/resources/http/request/local/Firebase.http
  src/main/resources/http/request/local/Mission.http
  src/main/resources/http/request/local/Rank.http
  src/main/resources/http/request/local/Stamp.http
  src/main/resources/http/request/local/UserBasic.http
  src/main/resources/http/request/local/UserNotification.http
  src/main/resources/http/request/local/UserOriginal.http
  src/main/resources/http/request/local/UserPushToken.http
Labels: enhancement, size/XXL

#90 Fix/#89 login rollback
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthController.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthRequest.java
  src/main/java/org/sopt/app/presentation/notification/PushTokenRequest.java
  src/main/java/org/sopt/app/presentation/user/UserNotificationController.java
  src/main/resources/http/request/Auth.http
  src/main/resources/http/request/local/UserPushToken.http
Labels: bug, size/M

#93 Feat/#80 active user ranking
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/mission/MissionInfo.java
  src/main/java/org/sopt/app/application/mission/MissionService.java
  src/main/java/org/sopt/app/application/rank/RankService.java
  src/main/java/org/sopt/app/application/soptamp/SoptampPointInfo.java
  src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserInfo.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/domain/entity/SoptampPoint.java
  src/main/java/org/sopt/app/domain/entity/SoptampUser.java
  src/main/java/org/sopt/app/domain/entity/User.java
  src/main/java/org/sopt/app/interfaces/postgres/SoptampPointRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/SoptampUserRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepository.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthController.java
  src/main/java/org/sopt/app/presentation/rank/RankController.java
  src/main/java/org/sopt/app/presentation/rank/RankResponseMapper.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
  src/main/java/org/sopt/app/presentation/user/UserController.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
  src/main/resources/database/create.sql
Labels: size/XL

#94 fix: 스탬프 등록 deprecated 변경 반영 #80
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
Labels: size/XS

#96 fix: soptamp missionRequest 수정
  src/main/java/org/sopt/app/application/stamp/StampFacade.java
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
  src/main/java/org/sopt/app/presentation/user/UserWithdrawController.java
Labels: size/L

#97 feat: firebase ios version 수정
  src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
Labels: size/S

#98 fix: current ranking 수정
  src/main/java/org/sopt/app/application/mission/MissionService.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
  src/main/java/org/sopt/app/interfaces/postgres/MissionRepository.java
Labels: size/S

#99 hotfix/current ranking api
  src/main/java/org/sopt/app/application/mission/MissionService.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
  src/main/java/org/sopt/app/interfaces/postgres/MissionRepository.java
  src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
Labels: size/S

#100 fix: soptamp user hotfix
  src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthController.java
Labels: size/XS

#101 fix: soptampPoint 로직 변경
  src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
  src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
Labels: size/S

#102 fix: ranking 조회 로직 수정
  src/main/java/org/sopt/app/presentation/rank/RankController.java
Labels: size/XS

#103 fix: 스탬프 조회하기 수정
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
Labels: size/XS

#104 fix: 스탬프 삭제하기 로직 수정
  src/main/java/org/sopt/app/application/stamp/StampFacade.java
Labels: size/XS

#105 hotfix/stamp 삭제 로직 수정
  src/main/java/org/sopt/app/application/stamp/StampFacade.java
Labels: size/XS

#106 fix: 비활동 기수 스탬프 삭제 로직 추가
  src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
Labels: size/S

#107 hotfix/비활동 기수 스탬프 삭제 로직 수정
  src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
Labels: size/S

#108 fix: 오타 수정
  src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
Labels: size/XS

#109 hotfix/오타 수정
  src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
Labels: size/XS
