Repository sopt-makers/sopt-backend, pull requests merged in 2024-01, with the labels that each got.

#198 fix: 온보딩 유저 추천 - 찌르기 여부 수정
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
Labels: size/M

#199 Fix/poke to me list
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
Labels: size/S

#202 Fix/friend creation policy
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/poke/PokeInfo.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
Labels: size/L

#200 fix: QA 1차 수정 - 친구 추천 로직 수정 및 친구의 친구 추천 로직 수정
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendCustomRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepositoryImpl.java
  src/main/java/org/sopt/app/interfaces/postgres/UserCustomRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepositoryImpl.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
Labels: size/L

#203 fix: 친구를 찔러보세요 - 친구 관계 변경 로직 대응
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
Labels: size/S

#204 fix: 새로운 유저 판별 로직 수정
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
Labels: size/S

#205 fix: 친구 여부 로직 수정
  src/main/java/org/sopt/app/application/poke/FriendService.java
Labels: size/XS

#206 Hotfix/friend
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
Labels: size/M

#208 fix: Controller 오타 수정
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
Labels: size/XS

#210 fix: 친구 없을 때 에러 대응 및 친구의 친구 로직 수정
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepositoryImpl.java
Labels: size/M

#212 FEAT : 친구가 아닌 유저 아이디로만 Shuffle 하도록 로직 추가
  src/main/java/org/sopt/app/facade/PokeFacade.java
Labels: size/XS

#213 fix: 친구 관계 숫자 범위 수정
  src/main/java/org/sopt/app/domain/enums/Friendship.java
Labels: size/XS

#214 Dev -> Main 머지
  .github/workflows/release-dev-code_deploy.yml
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthInfo.java
  src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/poke/FriendService.java
  src/main/java/org/sopt/app/application/poke/PokeEvent.java
  src/main/java/org/sopt/app/application/poke/PokeEventListener.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/poke/PokeInfo.java
  src/main/java/org/sopt/app/application/poke/PokeMessageService.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/application/user/UserInfo.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/config/QuerydslConfiguration.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/domain/entity/Friend.java
  src/main/java/org/sopt/app/domain/entity/PokeHistory.java
  src/main/java/org/sopt/app/domain/entity/PokeMessage.java
  src/main/java/org/sopt/app/domain/enums/Friendship.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageType.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageTypeConverter.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/external/PlaygroundClient.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendCustomRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepositoryImpl.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeMessageRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/UserRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeRequest.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
  src/main/java/org/sopt/app/presentation/user/UserRequest.java
  src/main/resources/database/create.sql
Labels: size/XXL
