Repository sopt-makers/sopt-backend, pull requests merged in 2024-09, with the labels that each got.

#339 refactor: 친구 추천 로직에 캐싱 도입
  build.gradle
  src/main/java/org/sopt/app/application/auth/dto/PlaygroundProfileInfo.java
  src/main/java/org/sopt/app/application/auth/dto/RecommendFriendRequest.java
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundHeaderCreator.java
  src/main/java/org/sopt/app/application/playground/PlaygroundUserRecommender.java
  src/main/java/org/sopt/app/application/playground/PlaygroundUserRecommenderRedisImpl.java
  src/main/java/org/sopt/app/application/poke/PokeInfo.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserInfo.java
  src/main/java/org/sopt/app/common/config/RedisConfig.java
  src/main/java/org/sopt/app/domain/entity/RecommendedUsers.java
  src/main/java/org/sopt/app/facade/AdminSoptampFacade.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
  src/main/java/org/sopt/app/facade/DescriptionFacade.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/facade/UserFacade.java
  src/main/java/org/sopt/app/interfaces/external/PlaygroundClient.java
  src/main/java/org/sopt/app/interfaces/postgres/RecommendedUserIdsRepository.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
  src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
  src/test/java/org/sopt/app/application/PlaygroundAuthServiceTest.java
  src/test/java/org/sopt/app/common/fixtures/PokeFixture.java
  src/test/java/org/sopt/app/facade/AuthFacadeTest.java
  src/test/java/org/sopt/app/facade/DescriptionFacadeTest.java
  src/test/java/org/sopt/app/facade/PokeFacadeTest.java
  src/test/java/org/sopt/app/facade/UserFacadeTest.java
Labels: size/L, 🔨 Refactor

#348 [FEAT] 모든 유저를 친구 추천하는 로직 추가
  src/main/java/org/sopt/app/application/auth/JwtTokenService.java
  src/main/java/org/sopt/app/application/auth/dto/RecommendFriendRequest.java
  src/main/java/org/sopt/app/application/friend/FriendFilter.java
  src/main/java/org/sopt/app/application/friend/FriendService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
  src/main/java/org/sopt/app/application/playground/PlaygroundUserRecommender.java
  src/main/java/org/sopt/app/application/playground/PlaygroundUserRecommenderRedisImpl.java
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundPostInfo.java
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundUserFindCondition.java
  src/main/java/org/sopt/app/application/playground/dto/RecommendedFriendInfo.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserFindConditionByGenerationCreator.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserFindConditionByMbtiCreator.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserFindConditionByUniversityCreator.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserFindConditionCreator.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserFindConditionCreatorFactory.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserFinder.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserFinderRedisImpl.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserIdsProvider.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/config/ClientConfig.java
  src/main/java/org/sopt/app/common/utils/RandomPicker.java
  src/main/java/org/sopt/app/domain/entity/RecommendedUserIds.java
  src/main/java/org/sopt/app/domain/enums/FriendRecommendType.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/RecommendedUserIdsRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/friend/FriendCustomRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/friend/FriendRepositoryImpl.java
  src/main/java/org/sopt/app/presentation/poke/PokeController.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
  src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
  src/test/java/org/sopt/app/application/FriendServiceTest.java
  src/test/java/org/sopt/app/application/PlaygroundAuthServiceTest.java
  src/test/java/org/sopt/app/application/UserServiceTest.java
  src/test/java/org/sopt/app/common/fixtures/PokeFixture.java
  src/test/java/org/sopt/app/facade/AuthFacadeTest.java
  src/test/java/org/sopt/app/facade/DescriptionFacadeTest.java
  src/test/java/org/sopt/app/facade/PokeFacadeTest.java
  src/test/java/org/sopt/app/facade/UserFacadeTest.java
  src/test/java/org/sopt/app/interfaces/postgres/FriendRepositoryTest.java
Labels: ✨ Feat, 🔨 Refactor, size/XXL

#345 [FEAT] 오늘의 솝마디 스케쥴러 구현 - #344
  src/main/java/org/sopt/app/AppApplication.java
  src/main/java/org/sopt/app/application/fortune/FortuneEvent.java
  src/main/java/org/sopt/app/application/fortune/FortuneEventListener.java
  src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/application/poke/PokeEventListener.java
  src/main/java/org/sopt/app/common/utils/HttpHeadersUtils.java
  src/main/java/org/sopt/app/presentation/fortune/FortuneAlarmRequest.java
  src/main/java/org/sopt/app/presentation/notification/NotificationRequest.java
Labels: ✨ Feat, size/L

#349 [FEAT] 친구 추천 테스트 추가
  src/main/java/org/sopt/app/application/friend/FriendFilter.java
  src/main/java/org/sopt/app/application/friend/FriendRecommender.java
  src/main/java/org/sopt/app/application/friend/FriendService.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserFindConditionCreatorFactory.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserIdsProvider.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/test/java/org/sopt/app/application/FriendRecommenderTest.java
  src/test/java/org/sopt/app/application/PlaygroundUserIdsProviderTest.java
  src/test/java/org/sopt/app/facade/PokeFacadeTest.java
Labels: ✨ Feat, 🔨 Refactor, size/XL

#350 [REFACTOR] Spring boot 2->3 migration 및 JAVA 21 도입 - #347
  .github/workflows/build-dev.yml
  .github/workflows/release-dev-code_deploy.yml
  .github/workflows/release-prod.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/org/sopt/app/AppApplication.java
  src/main/java/org/sopt/app/application/auth/JwtTokenService.java
  src/main/java/org/sopt/app/application/fortune/FortuneCardInfo.java
  src/main/java/org/sopt/app/application/fortune/FortuneEventListener.java
  src/main/java/org/sopt/app/application/poke/PokeEventListener.java
  src/main/java/org/sopt/app/application/s3/S3Service.java
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/common/config/JwtAuthenticationFilter.java
  src/main/java/org/sopt/app/common/config/JwtExceptionFilter.java
  src/main/java/org/sopt/app/common/config/QuerydslConfiguration.java
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
  src/main/java/org/sopt/app/common/response/CommonControllerAdvice.java
  src/main/java/org/sopt/app/domain/entity/AppService.java
  src/main/java/org/sopt/app/domain/entity/BaseEntity.java
  src/main/java/org/sopt/app/domain/entity/Friend.java
  src/main/java/org/sopt/app/domain/entity/MainDescription.java
  src/main/java/org/sopt/app/domain/entity/Notification.java
  src/main/java/org/sopt/app/domain/entity/PushToken.java
  src/main/java/org/sopt/app/domain/entity/User.java
  src/main/java/org/sopt/app/domain/entity/fortune/FortuneCard.java
  src/main/java/org/sopt/app/domain/entity/fortune/FortuneWord.java
  src/main/java/org/sopt/app/domain/entity/fortune/UserFortune.java
  src/main/java/org/sopt/app/domain/entity/poke/PokeHistory.java
  src/main/java/org/sopt/app/domain/entity/poke/PokeMessage.java
  src/main/java/org/sopt/app/domain/entity/soptamp/Mission.java
  src/main/java/org/sopt/app/domain/entity/soptamp/SoptampPoint.java
  src/main/java/org/sopt/app/domain/entity/soptamp/SoptampUser.java
  src/main/java/org/sopt/app/domain/entity/soptamp/Stamp.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageTypeConverter.java
  src/main/java/org/sopt/app/interfaces/postgres/fortune/FortuneCardRepositoryImpl.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthController.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthRequest.java
  src/main/java/org/sopt/app/presentation/fortune/FortuneAlarmRequest.java
  src/main/java/org/sopt/app/presentation/fortune/FortuneCardResponse.java
  src/main/java/org/sopt/app/presentation/fortune/FortuneController.java
  src/main/java/org/sopt/app/presentation/mission/MissionController.java
  src/main/java/org/sopt/app/presentation/mission/MissionRequest.java
  src/main/java/org/sopt/app/presentation/notification/NotificationController.java
  src/main/java/org/sopt/app/presentation/notification/NotificationRequest.java
  src/main/java/org/sopt/app/presentation/notification/PushTokenRequest.java
  src/main/java/org/sopt/app/presentation/poke/PokeRequest.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
  src/main/java/org/sopt/app/presentation/stamp/StampRequest.java
  src/main/java/org/sopt/app/presentation/user/UserController.java
  src/main/java/org/sopt/app/presentation/user/UserPushTokenController.java
  src/main/java/org/sopt/app/presentation/user/UserRequest.java
  src/main/java/org/sopt/app/presentation/user/UserWithdrawController.java
Labels: 🧹 Chore, size/L, 🔨 Refactor

#353 [FIX] cors 구성 빈등록 (#351)
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
Labels: size/S

#354 [FIX] Cors 처리 (#351)
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
Labels: 🛠️ BugFix

#355 [FIX] cors 처리 (#351)
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
Labels: 🐞 Bug, size/S, 🛠️ BugFix

#356 [FIX] cors (#351)
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
Labels: size/S

#357 [FIX] cors 제거 (#351)
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
Labels: 🐞 Bug, 🛠️ BugFix

#358 [FIX] CORS (#351)
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
Labels: size/M

#359 [FIX] cors (#351)
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
Labels: size/M

#363 [FIX] api 반복요청 수정 - #362
  build.gradle
  src/main/java/org/sopt/app/common/config/ClientConfig.java
  src/main/java/org/sopt/app/common/config/RestTemplateConfig.java
Labels: 🐞 Bug, size/M, 🛠️ BugFix

#365 [FIX] Url Match Filter 등록 (#364)
  src/main/java/org/sopt/app/common/config/ServletRequestWrapperFilter.java
  src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
Labels: 🐞 Bug, size/M, 🛠️ BugFix

#367 [FIX] 콕찌르기 무한반복 에러 수정 - #366
  src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/domain/entity/Friend.java
  src/main/java/org/sopt/app/domain/entity/poke/PokeHistory.java
  src/main/java/org/sopt/app/domain/entity/poke/PokeMessage.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
Labels: 🐞 Bug, 🧹 Chore, 🛠️ BugFix

#370 [FIX] fortune 알람 딥링크 수정 (#369)
  src/main/java/org/sopt/app/application/fortune/FortuneEventListener.java
  src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
Labels: size/XS, 🔧 Modify

#371 [FIX] 딥링크 수정 (#369)
  src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
Labels: size/XS

#373 [HOTFIX] FortuneWord가 아닌 FortuneCard id를 가져오는 로직 수정
  src/main/java/org/sopt/app/interfaces/postgres/fortune/FortuneCardRepositoryImpl.java
Labels: 🐞 Bug, size/XS, 🚨 HotFix, 🛠️ BugFix

#374 [REFACTOR] 솝탬프 리팩토링
  src/main/java/org/sopt/app/application/rank/SoptampPartRankCalculator.java
  src/main/java/org/sopt/app/application/rank/SoptampUserRankCalculator.java
  src/main/java/org/sopt/app/application/soptamp/SoptampPointInfo.java
  src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserFinder.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserInfo.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
  src/main/java/org/sopt/app/application/user/UserInfo.java
  src/main/java/org/sopt/app/domain/entity/soptamp/Mission.java
  src/main/java/org/sopt/app/domain/entity/soptamp/SoptampPoint.java
  src/main/java/org/sopt/app/domain/entity/soptamp/SoptampUser.java
  src/main/java/org/sopt/app/facade/AdminSoptampFacade.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
  src/main/java/org/sopt/app/facade/RankFacade.java
  src/main/java/org/sopt/app/facade/SoptampFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/SoptampUserRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/soptamp_point/SoptampPointJpaRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/soptamp_point/SoptampPointRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/soptamp_point/SoptampPointRepositoryImpl.java
  src/main/java/org/sopt/app/presentation/admin/AdminSoptampResponse.java
  src/main/java/org/sopt/app/presentation/rank/RankController.java
  src/main/java/org/sopt/app/presentation/user/UserController.java
  src/test/java/org/sopt/app/application/S3ServiceTest.java
  src/test/java/org/sopt/app/application/SoptampPointServiceTest.java
  src/test/java/org/sopt/app/application/SoptampUserFinderTest.java
  src/test/java/org/sopt/app/application/SoptampUserServiceTest.java
  src/test/java/org/sopt/app/common/fixtures/SoptampPointFixture.java
  src/test/java/org/sopt/app/common/fixtures/SoptampUserFixture.java
  src/test/java/org/sopt/app/facade/AuthFacadeTest.java
  src/test/java/org/sopt/app/facade/RankFacadeTest.java
  src/test/java/org/sopt/app/facade/SoptampFacadeTest.java
  src/test/java/org/sopt/app/interfaces/postgres/SoptampPointRepositoryTest.java
Labels: 🔨 Refactor, size/XXL, ☁️ DB

#376 [REFACTOR] 웹링크 null로 변경 - #375
  src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
  src/main/java/org/sopt/app/common/config/LazyDataSourceConfiguration.java
Labels: 🧹 Chore, size/M

#379 [REFACTOR] ErrorHandler 설정 및 에러 수정 - #378
  src/main/java/org/sopt/app/application/auth/CustomUserDetailService.java
  src/main/java/org/sopt/app/application/auth/JwtTokenService.java
  src/main/java/org/sopt/app/application/fortune/FortuneProvider.java
  src/main/java/org/sopt/app/application/friend/FriendService.java
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/application/notification/PushTokenService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/application/s3/S3Service.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserFinder.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/config/JwtAuthenticationFilter.java
  src/main/java/org/sopt/app/common/config/JwtExceptionFilter.java
  src/main/java/org/sopt/app/common/config/LazyDataSourceConfiguration.java
  src/main/java/org/sopt/app/common/exception/BadRequestException.java
  src/main/java/org/sopt/app/common/exception/BaseException.java
  src/main/java/org/sopt/app/common/exception/InternalServerException.java
  src/main/java/org/sopt/app/common/exception/NotFoundException.java
  src/main/java/org/sopt/app/common/exception/UnauthorizedException.java
  src/main/java/org/sopt/app/common/response/CommonControllerAdvice.java
  src/main/java/org/sopt/app/common/response/CommonResponse.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/common/response/FailureResponse.java
  src/main/java/org/sopt/app/common/response/GlobalExceptionHandler.java
  src/main/java/org/sopt/app/domain/enums/Friendship.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageType.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageTypeConverter.java
  src/main/java/org/sopt/app/interfaces/postgres/fortune/FortuneCardRepositoryImpl.java
  src/main/java/org/sopt/app/interfaces/postgres/fortune/FortuneWordJpaRepository.java
  src/main/java/org/sopt/app/presentation/admin/AdminSoptampController.java
Labels: size/XL
