Repository sopt-makers/sopt-backend, pull requests merged in 2024-10, with the labels that each got.

#383 [REFACTOR] slack 알림 서비스 refactoring - #382
  src/main/java/org/sopt/app/application/slack/SlackService.java
  src/main/java/org/sopt/app/common/response/CommonControllerAdvice.java
  src/main/java/org/sopt/app/common/response/ExceptionWrapper.java
  src/main/java/org/sopt/app/common/response/GlobalExceptionHandler.java
  src/main/java/org/sopt/app/common/response/SlackLogger.java
  src/main/java/org/sopt/app/common/response/SlackLoggerAspect.java
  src/main/java/org/sopt/app/common/response/SlackMessageGenerator.java
  src/test/java/org/sopt/app/application/SlackServiceTest.java
Labels: size/L

#381 [CHORE] spring config 구성 등록 (#380)
  build.gradle
  src/main/resources/application.yml
Labels: size/S

#385 [REFACTOR] slack 알림 메세지 변경 -#384
  src/main/java/org/sopt/app/application/slack/SlackService.java
  src/main/java/org/sopt/app/common/response/SlackMessageGenerator.java
Labels: size/M

#388 [FIX] application-local -> application.yml (#387)
  .github/workflows/release-dev-code_deploy.yml
Labels: size/XS

#389 [FIX] rollback (#387)
  .github/workflows/release-dev-code_deploy.yml
Labels: size/XS

#391 [REFACTOR] 실제 알림 오도록 구현 - #390
  src/main/java/org/sopt/app/application/fortune/FortuneEventListener.java
  src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
  src/main/java/org/sopt/app/application/poke/PokeEventListener.java
Labels: size/M, 🔨 Refactor, 🔧 Modify

#398 [REFACTOR] remove deprecated api
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/application/poke/PokeEventListener.java
  src/main/java/org/sopt/app/application/poke/PokeInfo.java
  src/main/java/org/sopt/app/application/poke/PokeMessageService.java
  src/main/java/org/sopt/app/application/s3/S3Service.java
  src/main/java/org/sopt/app/common/config/AwsConfig.java
  src/main/java/org/sopt/app/common/config/ClientConfig.java
  src/main/java/org/sopt/app/common/config/EventsConfig.java
  src/main/java/org/sopt/app/common/config/JwtAuthenticationFilter.java
  src/main/java/org/sopt/app/common/config/JwtExceptionFilter.java
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/common/response/FailureResponse.java
  src/main/java/org/sopt/app/common/response/GlobalExceptionHandler.java
  src/main/java/org/sopt/app/common/response/SlackLoggerAspect.java
  src/main/java/org/sopt/app/common/utils/AnonymousImageGenerator.java
  src/main/java/org/sopt/app/common/utils/RandomPicker.java
  src/main/java/org/sopt/app/domain/entity/BaseEntity.java
  src/main/java/org/sopt/app/domain/entity/Notification.java
  src/main/java/org/sopt/app/domain/entity/RecommendedUserIds.java
  src/main/java/org/sopt/app/domain/entity/poke/PokeHistory.java
  src/main/java/org/sopt/app/domain/entity/poke/PokeMessage.java
  src/main/java/org/sopt/app/domain/entity/soptamp/SoptampPoint.java
  src/main/java/org/sopt/app/domain/entity/soptamp/Stamp.java
  src/main/java/org/sopt/app/domain/enums/Part.java
  src/main/java/org/sopt/app/domain/enums/PokeMessageTypeConverter.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/facade/SoptampFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/RecommendedUserIdsRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/fortune/FortuneCardRepositoryImpl.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthController.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthResponse.java
  src/main/java/org/sopt/app/presentation/config/ConfigResponse.java
  src/main/java/org/sopt/app/presentation/description/DescriptionController.java
  src/main/java/org/sopt/app/presentation/mission/MissionController.java
  src/main/java/org/sopt/app/presentation/notification/NotificationController.java
  src/main/java/org/sopt/app/presentation/notification/NotificationResponse.java
  src/main/java/org/sopt/app/presentation/notification/PushTokenResponse.java
  src/main/java/org/sopt/app/presentation/poke/PokeRequest.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
  src/main/java/org/sopt/app/presentation/user/UserController.java
  src/main/java/org/sopt/app/presentation/user/UserRequest.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
  src/test/java/org/sopt/app/application/S3ServiceTest.java
  src/test/java/org/sopt/app/facade/SoptampFacadeTest.java
Labels: 🧹 Chore, 🔨 Refactor, size/XL

#397 [FIX] 알림이 두 번 저장되는 에러 해결
  src/main/java/org/sopt/app/application/fortune/FortuneEvent.java
  src/main/java/org/sopt/app/application/fortune/FortuneNotificationSender.java
  src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/presentation/fortune/FortuneAlarmRequest.java
  src/main/java/org/sopt/app/presentation/notification/NotificationController.java
  src/test/java/org/sopt/app/application/DescriptionServiceTest.java
Labels: 🧹 Chore, size/L, 🔨 Refactor, 🛠️ BugFix

#395 [CHORE] PartScores 일급 컬렉션을 사용한 로직 수정
  src/main/java/org/sopt/app/application/rank/PartScores.java
  src/main/java/org/sopt/app/application/rank/SoptampPartRankCalculator.java
  src/main/java/org/sopt/app/domain/enums/Part.java
Labels: 🧹 Chore, size/M

#393 [REFACTOR] fortuneId -> fortuneWordId로 네이밍 변경 및 자잘한 리팩토링
  src/main/java/org/sopt/app/application/fortune/FortuneGenerator.java
  src/main/java/org/sopt/app/application/fortune/FortuneService.java
  src/main/java/org/sopt/app/application/fortune/FortuneWordIdGenerator.java
  src/main/java/org/sopt/app/domain/entity/fortune/UserFortune.java
  src/main/java/org/sopt/app/interfaces/postgres/fortune/FortuneCardRepositoryImpl.java
  src/main/java/org/sopt/app/presentation/fortune/FortuneController.java
Labels: 🧹 Chore, size/L, 🔨 Refactor

#400 [REFACTOR] 플그 로그인 과정 리팩토링 및 솝탬프 관련 정보 추가
  src/main/java/org/sopt/app/application/auth/JwtTokenService.java
  src/main/java/org/sopt/app/application/friend/FriendFilter.java
  src/main/java/org/sopt/app/application/friend/FriendRecommender.java
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserFinder.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
  src/main/java/org/sopt/app/application/user/UserInfo.java
  src/main/java/org/sopt/app/application/user/UserProfile.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/domain/entity/User.java
  src/main/java/org/sopt/app/domain/entity/soptamp/SoptampUser.java
  src/main/java/org/sopt/app/domain/enums/PlaygroundPart.java
  src/main/java/org/sopt/app/facade/AdminSoptampFacade.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
  src/main/java/org/sopt/app/facade/RankFacade.java
  src/main/java/org/sopt/app/facade/SoptampFacade.java
  src/main/java/org/sopt/app/facade/UserFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/SoptampUserRepository.java
  src/main/java/org/sopt/app/presentation/admin/AdminSoptampController.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthController.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthResponse.java
  src/main/java/org/sopt/app/presentation/auth/AppAuthResponseMapper.java
  src/main/java/org/sopt/app/presentation/notification/NotificationController.java
  src/main/java/org/sopt/app/presentation/notification/NotificationRequest.java
  src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
  src/test/java/org/sopt/app/application/PlaygroundAuthServiceTest.java
  src/test/java/org/sopt/app/application/SoptampUserServiceTest.java
  src/test/java/org/sopt/app/application/UserServiceTest.java
  src/test/java/org/sopt/app/common/fixtures/PokeFixture.java
  src/test/java/org/sopt/app/common/fixtures/SoptampUserFixture.java
  src/test/java/org/sopt/app/facade/AuthFacadeTest.java
  src/test/java/org/sopt/app/facade/PokeFacadeTest.java
  src/test/java/org/sopt/app/facade/RankFacadeTest.java
  src/test/java/org/sopt/app/facade/UserFacadeTest.java
Labels: 🔨 Refactor, size/XXL, 🔧 Modify

#405 [FIX] Feign을 위한 기본 생성자 추가
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
Labels: 🐞 Bug, size/XS, 🛠️ BugFix

#406 [FIX] Feign을 위한 기본 생성자 추가
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
Labels: 🐞 Bug, size/XS, 🛠️ BugFix

#407 [Fix] Feign 에러 해결
  src/test/java/org/sopt/app/application/UserServiceTest.java
  src/test/java/org/sopt/app/facade/AuthFacadeTest.java
Labels: 🐞 Bug, size/XS, 🛠️ BugFix

#408 [FIX] Feign에서 값을 받기 위한 기본 생성자 추가
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
Labels: 🐞 Bug, size/XS, 🛠️ BugFix

#409 [FIX] Feign에서 값을 받기 위한 기본 생성자 추가
  src/main/java/org/sopt/app/domain/entity/soptamp/SoptampUser.java
Labels: 🐞 Bug, size/XS, 🛠️ BugFix

#410 [FIX] Feign에서 값을 받기 위한 기본 생성자 추가
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
Labels: 🐞 Bug, size/XS, 🛠️ BugFix

#412 [FIX] token refresh error
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
  src/main/java/org/sopt/app/application/poke/PokeMessageService.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
  src/main/java/org/sopt/app/domain/entity/soptamp/SoptampUser.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
  src/test/java/org/sopt/app/application/SoptampUserServiceTest.java
  src/test/java/org/sopt/app/common/fixtures/SoptampUserFixture.java
Labels: 🐞 Bug, size/M, 🛠️ BugFix

#413 [fix] Enumerate 추가
  src/main/java/org/sopt/app/domain/entity/soptamp/SoptampUser.java
Labels: 🐞 Bug, size/XS, 🛠️ BugFix

#415 [fix] 임시조치 (#414)
  src/main/java/org/sopt/app/common/response/GlobalExceptionHandler.java
Labels: size/XS

#416 [FIX] 404 -> 400 Error 반환하게 변경 (#414)
  src/main/java/org/sopt/app/common/response/ErrorCode.java
Labels: 🐞 Bug, size/XS, 🛠️ BugFix

#418 [FEAT] 문의 Controller 구현 (#417)
  src/main/java/org/sopt/app/presentation/report/ReportController.java
Labels: ✨ Feat, size/S

#420 [MODIFY] 솝탬프 신고 url 조회 로직 수정
  src/main/java/org/sopt/app/common/config/OpenApiConfig.java
  src/main/java/org/sopt/app/facade/SoptampFacade.java
  src/main/java/org/sopt/app/presentation/report/ReportController.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
  src/main/java/org/sopt/app/presentation/stamp/StampResponse.java
Labels: size/M, 🔧 Modify

#422 [FIX] 솝탬프 닉네임 설정 오류 수정
  src/main/java/org/sopt/app/application/friend/FriendRecommender.java
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
  src/main/java/org/sopt/app/domain/enums/PlaygroundPart.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/test/java/org/sopt/app/application/SoptampUserServiceTest.java
Labels: 🐞 Bug, size/M, 🛠️ BugFix

#424 [FIX] 포인트 0으로 초기화 로직 추가
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
Labels: 🐞 Bug, size/XS, 🛠️ BugFix
