Repository sopt-makers/sopt-backend, pull requests merged in 2024-11, with the labels that each got.

#338 feat: findSumOfPointBySamePartAndGeneration 테스트 추가
  src/main/java/org/sopt/app/application/app_service/AppServiceInfo.java
  src/main/java/org/sopt/app/application/description/DescriptionInfo.java
  src/main/java/org/sopt/app/application/mission/MissionInfo.java
  src/main/java/org/sopt/app/application/notification/PushTokenService.java
  src/main/java/org/sopt/app/application/s3/S3Info.java
  src/main/java/org/sopt/app/application/stamp/StampInfo.java
  src/main/java/org/sopt/app/common/response/CommonResponse.java
  src/main/java/org/sopt/app/common/response/SlackMessageGenerator.java
  src/main/java/org/sopt/app/interfaces/postgres/soptamp_point/SoptampPointRepositoryImpl.java
  src/main/java/org/sopt/app/presentation/HealthCheckController.java
  src/main/java/org/sopt/app/presentation/config/ConfigController.java
  src/main/java/org/sopt/app/presentation/firebase/FirebaseResponse.java
  src/test/java/org/sopt/app/AppApplicationTests.java
  src/test/java/org/sopt/app/application/SlackServiceTest.java
  src/test/java/org/sopt/app/application/SoptampUserServiceTest.java
  src/test/java/org/sopt/app/common/fixtures/SoptampPointFixture.java
  src/test/java/org/sopt/app/interfaces/postgres/SoptampPointRepositoryTest.java
Labels: ✨ Feat, size/M

#426 [MODIFY] 유저 탈퇴시 이벤트 기반으로 삭제해야하는 데이터 삭제 처리 로직 추가
  src/main/java/org/sopt/app/application/fortune/FortuneService.java
  src/main/java/org/sopt/app/application/friend/FriendService.java
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/application/notification/PushTokenService.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/application/s3/S3Service.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
  src/main/java/org/sopt/app/application/stamp/StampDeletedEvent.java
  src/main/java/org/sopt/app/application/stamp/StampDeletedEventHandler.java
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/application/user/UserWithdrawEvent.java
  src/main/java/org/sopt/app/application/user/UserWithdrawService.java
  src/main/java/org/sopt/app/common/config/EventsConfig.java
  src/main/java/org/sopt/app/common/event/EventPublisher.java
  src/main/java/org/sopt/app/common/event/Events.java
  src/main/java/org/sopt/app/facade/SoptampFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/NotificationRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/SoptampUserRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/fortune/UserFortuneRepository.java
  src/main/java/org/sopt/app/presentation/user/UserWithdrawController.java
  src/test/java/org/sopt/app/application/EventPublisherTest.java
  src/test/java/org/sopt/app/application/PokeServiceTest.java
  src/test/java/org/sopt/app/application/S3ServiceTest.java
  src/test/java/org/sopt/app/application/SoptampUserFinderTest.java
  src/test/java/org/sopt/app/application/StampServiceTest.java
  src/test/java/org/sopt/app/application/UserServiceTest.java
  src/test/java/org/sopt/app/application/UserWithdrawTest.java
  src/test/resources/application.yml
Labels: 🔨 Refactor, size/XL, 🔧 Modify

#432 [FEAT] 메인 문구 조회 api 개발 완료
  src/main/java/org/sopt/app/application/description/DescriptionInfo.java
  src/main/java/org/sopt/app/application/description/DescriptionService.java
  src/main/java/org/sopt/app/application/home/ActivityDurationCalculator.java
  src/main/java/org/sopt/app/facade/HomeFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/MainDescriptionRepository.java
  src/main/java/org/sopt/app/presentation/description/DescriptionController.java
  src/main/java/org/sopt/app/presentation/home/HomeController.java
  src/main/java/org/sopt/app/presentation/home/HomeDescriptionResponse.java
  src/test/java/org/sopt/app/facade/HomeFacadeTest.java
Labels: ✨ Feat, size/L

#438 [FEAT] 알림 목록 카테고리 별 조회 기능 추가
  src/main/java/org/sopt/app/application/notification/NotificationService.java
  src/main/java/org/sopt/app/interfaces/postgres/NotificationRepository.java
  src/main/java/org/sopt/app/presentation/notification/NotificationController.java
Labels: ✨ Feat, size/S, 🔧 Modify

#439 [FEAT] 일정 전체 보기 기능 추가
  src/main/java/org/sopt/app/application/calendar/CalendarService.java
  src/main/java/org/sopt/app/application/calendar/CalendarServiceImpl.java
  src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserFinderRedisImpl.java
  src/main/java/org/sopt/app/common/config/RedisConfig.java
  src/main/java/org/sopt/app/domain/cache/CachedAllCalendarResponse.java
  src/main/java/org/sopt/app/domain/cache/CachedRecommendedUserIds.java
  src/main/java/org/sopt/app/domain/cache/Calendars.java
  src/main/java/org/sopt/app/domain/entity/Calendar.java
  src/main/java/org/sopt/app/domain/enums/CalendarType.java
  src/main/java/org/sopt/app/interfaces/postgres/CalendarRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/RecommendedUserIdsRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/redis/CachedCalendarRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/redis/CachedRecommendedUserIdsRepository.java
  src/main/java/org/sopt/app/presentation/calendar/CalendarController.java
  src/main/java/org/sopt/app/presentation/calendar/CalendarResponse.java
Labels: ✨ Feat, size/L

#442 [FEAT] 앱 서비스 진입 여부 조회 로직 추가
  src/main/java/org/sopt/app/application/app_service/AppServiceBadgeManager.java
  src/main/java/org/sopt/app/application/app_service/AppServiceBadgeService.java
  src/main/java/org/sopt/app/application/app_service/AppServiceInfo.java
  src/main/java/org/sopt/app/application/app_service/AppServiceName.java
  src/main/java/org/sopt/app/application/app_service/AppServiceService.java
  src/main/java/org/sopt/app/application/app_service/DefaultBadgeManager.java
  src/main/java/org/sopt/app/application/app_service/FortuneBadgeManager.java
  src/main/java/org/sopt/app/application/app_service/PokeBadgeManager.java
  src/main/java/org/sopt/app/application/app_service/SoptampBadgeManager.java
  src/main/java/org/sopt/app/application/app_service/dto/AppServiceBadgeInfo.java
  src/main/java/org/sopt/app/application/app_service/dto/AppServiceEntryStatusResponse.java
  src/main/java/org/sopt/app/application/app_service/dto/AppServiceInfo.java
  src/main/java/org/sopt/app/application/fortune/FortuneService.java
  src/main/java/org/sopt/app/application/home/ActivityDurationCalculator.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/soptamp/SoptampPointInfo.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserInfo.java
  src/main/java/org/sopt/app/common/utils/CurrentDate.java
  src/main/java/org/sopt/app/domain/entity/AppService.java
  src/main/java/org/sopt/app/domain/enums/PlaygroundPart.java
  src/main/java/org/sopt/app/facade/HomeFacade.java
  src/main/java/org/sopt/app/facade/RankFacade.java
  src/main/java/org/sopt/app/facade/UserFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/home/HomeController.java
  src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
Labels: ✨ Feat, size/L

#445 [MODIFY] 일정이 끝났을 때, 일정 관련 api에서 가장 마지막 일정을 반환하도록 수정
  src/main/java/org/sopt/app/application/calendar/CalendarServiceImpl.java
  src/main/java/org/sopt/app/presentation/calendar/CalendarResponse.java
Labels: size/M

#443 [FEAT] 플레이그라운드 채용정보 조회 기능 API - #436
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
  src/main/java/org/sopt/app/application/playground/dto/PlayGroundEmploymentResponse.java
  src/main/java/org/sopt/app/facade/HomeFacade.java
  src/main/java/org/sopt/app/presentation/home/HomeController.java
  src/main/java/org/sopt/app/presentation/home/response/EmploymentPostResponse.java
Labels: size/L

#446 [FEAT] 전체 모임 확인 dummy api 추가
  src/main/java/org/sopt/app/application/meeting/MeetingCategory.java
  src/main/java/org/sopt/app/application/meeting/MeetingResponse.java
  src/main/java/org/sopt/app/application/meeting/MeetingStatus.java
  src/main/java/org/sopt/app/presentation/home/HomeController.java
Labels: size/L

#447 [FEAT] 카테고리별 최신 게시물 조회 API 구현 - #434
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
  src/main/java/org/sopt/app/application/playground/dto/PlayGroundPostCategory.java
  src/main/java/org/sopt/app/facade/HomeFacade.java
  src/main/java/org/sopt/app/presentation/home/HomeController.java
  src/main/java/org/sopt/app/presentation/home/response/RecentPostsResponse.java
Labels: ✨ Feat, size/L

#450 [HOTFIX] 플레이그라운드아이디가 유효하지 않은 친구 추천시 에러 발생 오류 해결
  src/main/java/org/sopt/app/application/friend/FriendRecommender.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/M, 🛠️ BugFix

#452 [FIX] 솝탬프 contents가 empty이면 오류가 발생하는 에러 해결
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/presentation/stamp/StampRequest.java
Labels: size/M, 🛠️ BugFix

#451 [MERGE] HOTFIX 내용 dev에도 반영
  src/main/java/org/sopt/app/application/friend/FriendRecommender.java
  src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
Labels: size/M

#457 [MODIFY] 기획 변경으로 인한 앱 서비스 반환 API 수정
  src/main/java/org/sopt/app/application/app_service/AppServiceBadgeService.java
  src/main/java/org/sopt/app/application/app_service/AppServiceName.java
  src/main/java/org/sopt/app/application/app_service/FortuneBadgeManager.java
  src/main/java/org/sopt/app/application/app_service/PokeBadgeManager.java
  src/main/java/org/sopt/app/application/app_service/SoptampBadgeManager.java
  src/main/java/org/sopt/app/application/app_service/dto/AppServiceBadgeInfo.java
  src/main/java/org/sopt/app/application/app_service/dto/AppServiceEntryStatusResponse.java
  src/main/java/org/sopt/app/application/app_service/dto/AppServiceInfo.java
  src/main/java/org/sopt/app/domain/entity/AppService.java
Labels: size/L, 🔧 Modify

#453 [REFACTOR] 플레이그라운드 게시물 반환 기능 + 채용 정보 조회 사용자 정보 추가 - #434
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
  src/main/java/org/sopt/app/application/playground/dto/PlayGroundPostDetailResponse.java
  src/main/java/org/sopt/app/application/playground/dto/PostWithMemberInfo.java
  src/main/java/org/sopt/app/facade/HomeFacade.java
  src/main/java/org/sopt/app/presentation/home/HomeController.java
  src/main/java/org/sopt/app/presentation/home/response/EmploymentPostResponse.java
  src/main/java/org/sopt/app/presentation/home/response/RecentPostsResponse.java
Labels: ✨ Feat, size/L, 🔧 Modify

#448 [FEAT] 커피챗 등록 유저들 리스트 조회 API - #435
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
  src/main/java/org/sopt/app/application/playground/dto/PlayGroundCoffeeChatResponse.java
  src/main/java/org/sopt/app/application/playground/dto/PlayGroundCoffeeChatWrapper.java
  src/main/java/org/sopt/app/facade/HomeFacade.java
  src/main/java/org/sopt/app/presentation/home/HomeController.java
  src/main/java/org/sopt/app/presentation/home/response/CoffeeChatResponse.java
Labels: size/L

#458 [FEAT] 모든 모임 조회 api 크루 api와 연결
  src/main/java/org/sopt/app/application/meeting/CrewClient.java
  src/main/java/org/sopt/app/application/meeting/CrewMeetingResponse.java
  src/main/java/org/sopt/app/application/meeting/MeetingCategory.java
  src/main/java/org/sopt/app/application/meeting/MeetingResponse.java
  src/main/java/org/sopt/app/application/meeting/MeetingService.java
  src/main/java/org/sopt/app/application/meeting/MeetingStatus.java
  src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
  src/main/java/org/sopt/app/common/config/ClientConfig.java
  src/main/java/org/sopt/app/facade/HomeFacade.java
  src/main/java/org/sopt/app/presentation/home/HomeController.java
  src/main/java/org/sopt/app/presentation/home/MeetingParamRequest.java
  src/main/java/org/sopt/app/presentation/home/response/HomeDescriptionResponse.java
Labels: ✨ Feat, size/L

#461 [MODIFY] 모든 파트 가져오기 기능에서 joinableParts 필드가 한글로 반환되도록 수정
  src/main/java/org/sopt/app/application/meeting/CrewMeetingResponse.java
  src/main/java/org/sopt/app/application/meeting/CrewPart.java
  src/main/java/org/sopt/app/application/meeting/MeetingResponse.java
  src/main/java/org/sopt/app/facade/HomeFacade.java
Labels: size/M, 🔧 Modify
