Repository sopt-makers/sopt-backend, pull requests merged in 2025-09, with the labels that each got.

#578 [DEPLOY] #573 - 배포 pipeline 관련 수정
  .github/workflows/release-prod.yml
  Dockerfile-prod
Labels: 🚀 Deploy

#579 [DEPLOY] #573 - 배포 pipeline 관련 수정
  .github/workflows/release-prod.yml
  Dockerfile-prod
Labels: size/XS

#580 [FIX] #573 - prod cd user 및 경로 수정
  .github/workflows/release-prod.yml
Labels: size/S, 🛠️ BugFix

#582 [DEPLOY] #574 - deploy.sh 수정
  script/deploy.sh
Labels: 🚀 Deploy, size/S

#584 [FIX] #575 - 첫 배포 시 종료되는 문제 수정
  script/deploy.sh
Labels: 🚀 Deploy, size/XS, 🛠️ BugFix

#585 [FIX] #575 - 첫 배포 시 종료되는 문제 수정
  script/deploy.sh
Labels: 🚀 Deploy, size/XS, 🛠️ BugFix

#594 [Feat] #593 - 플그관련 default 유저 삭제 Internal api 구현
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/security/config/WebSecurityConfig.java
  src/main/java/org/sopt/app/facade/UserFacade.java
  src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
Labels: ✨ Feat, size/M

#601 [deploy] #600 - ECR 이전 이미지 자동 삭제를 위한 workflow 수정
  .github/workflows/app-cd-dev.yml
Labels: 🚀 Deploy, size/XS

#603 [DEPLOY] #602 - ECR 퍼블릭 레포지토리로 지정 및 region 추가
  .github/workflows/app-cd-dev.yml
Labels: 🚀 Deploy, size/XS

#605 [DEPLOY] #604 - ECR에서 dev 이미지 가져오는 스크립트 수정
  .github/workflows/app-cd-dev.yml
Labels: 🚀 Deploy, size/XS

#608 [deploy] - 콕찌르기/Platform 연동 안정화 & Slack 로깅 예외 방지 prod 배포
  .github/workflows/app-cd-dev.yml
  src/main/java/org/sopt/app/application/platform/PlatformClient.java
  src/main/java/org/sopt/app/application/platform/PlatformService.java
  src/main/java/org/sopt/app/application/platform/dto/PlatformUserIdsRequest.java
  src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/common/response/SlackLoggerAspect.java
  src/main/java/org/sopt/app/common/security/config/WebSecurityConfig.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/facade/UserFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/internal/UserInternalController.java
  src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
Labels: 🚀 Deploy, size/L

#617 [fix] #616 - 솝탬프 순위 계산 로직 수정
  src/main/java/org/sopt/app/application/rank/SoptampUserRankCalculator.java
Labels: size/XS, 🛠️ BugFix

#620 [fix] #619 - SoptampUser 의 안드로이드 파트명 prefix 수정
  src/main/java/org/sopt/app/application/app_service/SoptampBadgeManager.java
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
  src/main/java/org/sopt/app/application/rank/CachedUserInfo.java
  src/main/java/org/sopt/app/application/rank/RankScheduler.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserInfo.java
  src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
  src/main/java/org/sopt/app/domain/entity/soptamp/SoptampUser.java
  src/main/java/org/sopt/app/domain/enums/SoptPart.java
  src/main/java/org/sopt/app/presentation/user/UserController.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
Labels: size/M
