Repository sopt-makers/sopt-backend, pull requests merged in 2025-04, with the labels that each got.

#522 [Fix] 솝탬프 랭크 null인 경우 문자열 처리
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
Labels: 🧹 Chore, size/XS

#524 [FIX] 홈화면 최신 행사 일정 관련 이슈 - #523
  src/main/java/org/sopt/app/application/calendar/CalendarServiceImpl.java
  src/main/java/org/sopt/app/application/fortune/FortuneService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/utils/ActivityDurationCalculator.java
  src/main/java/org/sopt/app/common/utils/CurrentDate.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
Labels: size/M, 🛠️ BugFix

#526 [DEPLOY] QA 변경사항 Prod 배포
  src/main/java/org/sopt/app/application/calendar/CalendarServiceImpl.java
  src/main/java/org/sopt/app/application/fortune/FortuneService.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/common/utils/ActivityDurationCalculator.java
  src/main/java/org/sopt/app/common/utils/CurrentDate.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
Labels: 🚀 Deploy, size/M

#528 [Fix] 솝트로그, 솝탬프 관련 이슈 해결 (#527)
  src/main/java/org/sopt/app/presentation/user/UserController.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
Labels: size/M, 🛠️ BugFix

#530 [Refactor] 솝탬프 관련 로직 리팩토링 - #529
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/common/exception/ForbiddenException.java
  src/main/java/org/sopt/app/common/response/ErrorCode.java
  src/main/java/org/sopt/app/domain/entity/soptamp/Stamp.java
  src/main/java/org/sopt/app/facade/SoptampFacade.java
  src/main/java/org/sopt/app/presentation/stamp/StampController.java
  src/main/java/org/sopt/app/presentation/stamp/StampRequest.java
  src/test/java/org/sopt/app/facade/SoptampFacadeTest.java
Labels: size/L, 🔨 Refactor

#536 [CHORE] 솝탬프 관련 로깅 추가 - #535
  src/main/java/org/sopt/app/facade/SoptampFacade.java
Labels: size/S

#537 [CHORE] 로깅 레벨 변경 - #535
  src/main/java/org/sopt/app/facade/SoptampFacade.java
Labels: 🧹 Chore

#539 [Deploy] docker 배포 관련 수정 - #538
  .github/workflows/app-cd-dev.yml
  Dockerfile
Labels: 🚀 Deploy

#540 [DEPLOY] docker build 옵션 변경- #538
  .github/workflows/app-cd-dev.yml
Labels: 🚀 Deploy, size/XS

#541 Revert "[DEPLOY] docker build 옵션 변경- #538"
  .github/workflows/app-cd-dev.yml
Labels: size/XS

#542 Revert "[Deploy] docker 배포 관련 수정 - #538"
  Dockerfile
Labels: size/XS

#544 [FIX] Dockerfile 수정 - #538
  Dockerfile
Labels: 🚀 Deploy, size/XS, 🛠️ BugFix

#546 [CHORE] 불필요한 로깅 제거 - #545
  src/main/java/org/sopt/app/facade/SoptampFacade.java
Labels: 🧹 Chore

#547 [DEPLOY] QA 변경사항 Prod 배포
  .github/workflows/app-cd-dev.yml
  Dockerfile
  src/main/java/org/sopt/app/application/stamp/StampService.java
  src/main/java/org/sopt/app/facade/SoptampFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/StampRepository.java
  src/test/java/org/sopt/app/facade/SoptampFacadeTest.java
Labels: size/S

#549 [Fix] AWS Credential 시크릿에서 주입받아 배포하도록 수정 (#548)
  .github/workflows/app-cd-dev.yml
  src/main/java/org/sopt/app/common/config/AwsConfig.java
Labels: size/S, 🛠️ BugFix

#550 [Fix] AWS SDK v2 마이그레이션 (#548)
  build.gradle
  src/main/java/org/sopt/app/application/auth/JwtTokenService.java
  src/main/java/org/sopt/app/application/s3/S3Service.java
  src/main/java/org/sopt/app/common/config/AwsConfig.java
  src/test/java/org/sopt/app/application/S3ServiceTest.java
Labels: size/L
