Repository sopt-makers/sopt-backend, pull requests merged in 2025-03, with the labels that each got.

#494 [HOTFIX] User Entity에 고정된 스키마명 변경
  src/main/java/org/sopt/app/domain/entity/User.java
Labels: size/XS, 🛠️ BugFix

#495 [DEPLOY] dev환경 docker를 이용한 무중단 배포 방식으로 변경
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/workflows/app-cd-dev.yml
  .github/workflows/app-ci.yml
  .github/workflows/build-dev.yml
  .github/workflows/release-dev-code_deploy.yml
  .github/workflows/release-prod.yml
  .gitignore
  Dockerfile
  script/deploy.sh
  script/deploy_container.sh
  script/health_check.sh
  script/nginx_reload.sh
  script/start.sh
  script/stop.sh
  script/stop_container.sh
Labels: 🚀 Deploy, size/L

#496 [MODIFY] prod와 dev가 같은 AWS key를 사용하도록 변경
  .github/workflows/app-cd-dev.yml
Labels: 🚀 Deploy, size/XS

#497 [FIX] script 폴더명 오타 수정
  .github/workflows/app-cd-dev.yml
Labels: 🚀 Deploy, size/XS

#498 [FIX] script 폴더명 오타 수정
  .github/workflows/app-cd-dev.yml
  script/deploy.sh
Labels: 🚀 Deploy, size/S

#499 [MODIFY] health check시에 RETRIES 시간 증가
  script/deploy_container.sh
  script/health_check.sh
Labels: 🚀 Deploy, size/XS

#501 [Docs] Generation 수정 및 PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs, 🚀 Deploy, size/S

#503 [Feat] CalendarType 추가
  src/main/java/org/sopt/app/domain/enums/CalendarType.java
Labels: size/XS, 🔧 Modify, ☁️ DB

#505 [FEAT] 플레이그라운드 카테고리별 게시물 조회 api에 url 추가 - #504
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/presentation/home/response/RecentPostsResponse.java
  src/test/java/org/sopt/app/application/PlaygroundAuthServiceTest.java
Labels: ✨ Feat, size/L, 🔨 Refactor

#512 [FIX] 활동 기간 계산 로직 통일 및 ActivityDurationCalculator 유틸화 - #511
  src/main/java/org/sopt/app/application/home/ActivityDurationCalculator.java
  src/main/java/org/sopt/app/common/utils/ActivityDurationCalculator.java
  src/main/java/org/sopt/app/facade/HomeFacade.java
  src/main/java/org/sopt/app/presentation/user/UserController.java
Labels: size/L, 🔨 Refactor, 🛠️ BugFix

#514 [Fix] 솝트로그 아이콘 정렬 추가 (#513)
  src/main/java/org/sopt/app/presentation/user/UserController.java
Labels: size/S, 🛠️ BugFix

#517 [Fix] 플그로 로그인 시 soptamp 관련 로직 무조건 통과하도록 변경 및 테스트용 로그 삭제 (#516)
  src/main/java/org/sopt/app/facade/AuthFacade.java
Labels: size/XS, 🛠️ BugFix

#520 [Fix] 솝트로그 관련 이슈 해결 (#519)
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
  src/main/java/org/sopt/app/presentation/user/UserController.java
Labels: size/M, 🛠️ BugFix
