Repository sopt-makers/sopt-backend, pull requests merged in 2025-01, with the labels that each got.

#465 [FIX] /error에 대해 인증없이 접근을 허용하도록 변경
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
Labels: size/XS, 🛠️ BugFix

#469 [MODIFY] 매주 월요일에 솝마디 알림이 가도록 변경
  src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
Labels: size/XS, 🔧 Modify

#471 [MODIFY] /user/main시에 로그인되지 않은 유저는 401이 아닌 정상 응답을 보내도록 변경
  src/main/java/org/sopt/app/application/operation/OperationInfo.java
  src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
  src/main/java/org/sopt/app/facade/UserFacade.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
  src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
  src/test/java/org/sopt/app/facade/UserFacadeTest.java
Labels: size/M, 🔧 Modify

#459 [FEAT] 솝트 로그 API 개발 - #437
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
  src/main/java/org/sopt/app/application/playground/dto/PlayGroundUserSoptLevelResponse.java
  src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
  src/main/java/org/sopt/app/application/poke/PokeService.java
  src/main/java/org/sopt/app/application/rank/SoptampUserRankCalculator.java
  src/main/java/org/sopt/app/application/user/UserService.java
  src/main/java/org/sopt/app/domain/entity/Icons.java
  src/main/java/org/sopt/app/domain/enums/IconType.java
  src/main/java/org/sopt/app/facade/AuthFacade.java
  src/main/java/org/sopt/app/facade/PokeFacade.java
  src/main/java/org/sopt/app/facade/RankFacade.java
  src/main/java/org/sopt/app/interfaces/postgres/IconRepository.java
  src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
  src/main/java/org/sopt/app/presentation/user/UserController.java
  src/main/java/org/sopt/app/presentation/user/UserResponse.java
  src/test/java/org/sopt/app/facade/PokeFacadeTest.java
Labels: size/L

#476 [MODIFY] 일정 전체 보기 반환 형식 변경
  src/main/java/org/sopt/app/application/calendar/CalendarServiceImpl.java
  src/main/java/org/sopt/app/presentation/calendar/CalendarResponse.java
  src/main/java/org/sopt/app/presentation/calendar/DateFormatter.java
Labels: size/M, 🔧 Modify

#475 [MODIFY] 메인 문구 조회시 \n을 <br>로 변경
  src/main/java/org/sopt/app/presentation/home/response/HomeDescriptionResponse.java
Labels: size/XS, 🔧 Modify

#463 [MODIFY] 커피챗 API 변경 (#462)
  src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
  src/main/java/org/sopt/app/presentation/home/response/CoffeeChatResponse.java
Labels: size/S, 🔧 Modify
